name: Build and Test

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  prepare-container:
    # This job has the following matrix, x: Job trigger, y: Branch
    # (scheduled jobs run only on main):
    # +-------+-------------------+-------------------+
    # |       | Push/Pull request |     Scheduled     |
    # +-------+-------------------+-------------------+
    # |  main |  ghcr.io - Ubuntu | ghcr.io - Fedora  |
    # +-------+-------------------+-------------------+
    # | !main |  Builds - Ubuntu  | xxxxxxxxxxxxxxxxx |
    # +-------+-------------------+-------------------+
    env:
      DEPENDENCIES: podman
    name: Prepare container
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Update APT cache
        run: sudo apt update

      - name: Install dependencies
        run: sudo apt install -y fio

      - name: Fio
        run: |
          fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --bs=4k --iodepth=64 --readwrite=randrw --rwmixread=75 --size=4G --filename=testfile

